# Generated by Django 6.0.2 on 2026-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Survey Creator'), ('respondent', 'Respondent')], default='user', max_length=10),
        ),
    ]
