# Generated by Django 6.0.2 on 2026-02-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('creator', 'Survey Creator'), ('respondent', 'Respondent')], default='user', max_length=10),
        ),
    ]
