# Generated by Django 6.0.2 on 2026-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CREATOR', 'Survey Creator'), ('RESPONDENT', 'Respondent')], default='user', max_length=10),
        ),
    ]
