# Generated by Django 6.0.2 on 2026-03-27 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_builder_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameIndex(
            model_name='canvaselement',
            new_name='survey_canv_survey__b79ec9_idx',
            old_name='survey_canv_survey__5cf981_idx',
        ),
        migrations.RenameIndex(
            model_name='canvaselement',
            new_name='survey_canv_survey__c9f5a1_idx',
            old_name='survey_canv_survey__c1fd96_idx',
        ),
        migrations.RenameIndex(
            model_name='option',
            new_name='survey_opti_questio_57d4aa_idx',
            old_name='survey_opti_questio_4f7a5d_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='survey_ques_survey__5b55d8_idx',
            old_name='survey_ques_survey__d17cb8_idx',
        ),
        migrations.RenameIndex(
            model_name='survey',
            new_name='survey_surv_created_1bf341_idx',
            old_name='survey_surv_created_8d63f2_idx',
        ),
        migrations.RenameIndex(
            model_name='survey',
            new_name='survey_surv_is_publ_3718a4_idx',
            old_name='survey_surv_is_publ_3cf3e4_idx',
        ),
        migrations.RenameIndex(
            model_name='survey',
            new_name='survey_surv_share_t_c5cfe1_idx',
            old_name='survey_surv_share_t_2802cf_idx',
        ),
        migrations.AlterField(
            model_name='canvaselement',
            name='element_type',
            field=models.CharField(choices=[('question', 'Question'), ('text', 'Text'), ('image', 'Image'), ('divider', 'Divider')], max_length=20),
        ),
        migrations.AlterField(
            model_name='canvaselement',
            name='height',
            field=models.FloatField(default=140),
        ),
        migrations.AlterField(
            model_name='canvaselement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='canvaselement',
            name='width',
            field=models.FloatField(default=320),
        ),
        migrations.AlterField(
            model_name='canvaselement',
            name='x',
            field=models.FloatField(default=24),
        ),
        migrations.AlterField(
            model_name='canvaselement',
            name='y',
            field=models.FloatField(default=24),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(default='Untitled Survey', max_length=255),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_survey_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='structure',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
